### PR TITLE
Isoform suggestions

### PR DESCRIPTION
**Pull request by lldelisle**
I started to implement changes we talk about. You will be able to select what you want.

### CODE REVIEW

**Comment by lldelisle** [comment]
I have different results from you... I don't know why... I think to make the tutorial more easy to update it would be good if you could provide the R script to generate the different ggplot or if you did it in galaxy how did you do it...

**Comment by lldelisle** [comment]
I let you comment on the pyGenomeTracks plot and integrate it to the tutorial.

**Comment by lldelisle** [comment]
Yes sorry I forgot to remove the [WIP]

**Comment by lldelisle** [comment]
However, as a general comment, I found this tutorial very long to run. Would it be possible to subset more the reads? Maybe using the trick I described [here in example2 ](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial/tutorial.html#get-a-toy-dataset)

**Comment by gallardoalba** [comment]
> However, as a general comment, I found this tutorial very long to run. Would it be possible to subset more the reads? Maybe using the trick I described [here in example2 ](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial/tutorial.html#get-a-toy-dataset)

Yes, I'll try to generate a toy dataset; I tried to reduce but the results were not significant. Could you share your history with me? I would like to check why the results were so different.

**Comment by gallardoalba** [comment]
> I tried to share it with your account on usegalaxy.eu. I also try to contact you through matrix, I don't know if you are using it.

Yes, my userid in matrix is gallardoalba.

**Comment by gallardoalba** [comment]
I'll merge, but but since it mixed up the Gencode version, probably I will include some additional minor modifications. Thanks a lot for the review!

**Comment by lldelisle** [comment]
You're welcome. Do not hesitate to ping me for a second review.

**Pull request merged**
